@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

TbmManager *-right-> "1" UniqueClientList

UniqueClientList o-right-> Client

Client *--> Name
Client *--> Phone
Client *--> Email
Client *--> Address
Client *--> "ObservableList<Note>"
@enduml
